name: tupynambalucas-monitor

services:
  otel-collector:
    profiles: ['dev', 'prod', 'staging']
    image: otel/opentelemetry-collector-contrib:latest
    container_name: tupynambalucas-monitor-otel-${APP_ENV:-prod}
    command: ['--config=/etc/otelcol-contrib/config.yaml']
    volumes:
      - ../../gateway/monitor-gateway.yaml:/etc/otelcol-contrib/config.yaml:ro
    ports:
      - '24224:24224'
    environment:
      # Injetando as variáveis do .env para dentro do container para uso do OTel
      - GRAFANA_CLOUD_OTLP_ENDPOINT=${GRAFANA_CLOUD_OTLP_ENDPOINT}
      - GRAFANA_CLOUD_TOKEN=${GRAFANA_CLOUD_TOKEN}
      - SENTRY_OTLP_ENDPOINT=${SENTRY_OTLP_ENDPOINT}
      - SENTRY_AUTH_HEADER=${SENTRY_AUTH_HEADER}
    networks:
      - tupynambalucas-monitor-net

networks:
  tupynambalucas-monitor-net:
    name: tupynambalucas-monitor-net
    external: true
