base_path: .
preserve_hierarchy: true
files:
  - source: /knowledge-base/collections/namespaces/portal/content/**/*.mdx
    type: mdx
    translation: /knowledge-base/collections/namespaces/portal/locales/%locale%/**/%original_file_name%
