base_path: .
preserve_hierarchy: true
pull_request_title: "chore(l10n): synchronize translations"
pull_request_labels:
  - "l10n"
  - "documentation"
commit_message: "chore(l10n): update translations [ci skip]"
files:
  - source: /knowledge-base/collections/namespaces/portal/content/**/*.mdx
    translation: /knowledge-base/collections/namespaces/portal/locales/%locale%/**/%original_file_name%
  - source: /knowledge-base/collections/namespaces/portal/content/messages/**/*.json
    translation: /knowledge-base/collections/namespaces/portal/locales/%locale%/messages/**/%original_file_name%
    type: chrome
