"base_path": "."
"preserve_hierarchy": true

files:
  # ---------------------------------------------------------
  # Knowledge Base: Portal
  # ---------------------------------------------------------
  - source: '/knowledge-base/collections/namespaces/portal/content/**/*.mdx'
    type: 'mdx'
    translation: '/knowledge-base/collections/namespaces/portal/locales/%locale%/**/%original_file_name%'

  # ---------------------------------------------------------
  # Futuros Namespaces (Exemplo de como adicionar)
  # ---------------------------------------------------------
  # - source: '/knowledge-base/collections/namespaces/blog/content/**/*.mdx'
  #   translation: '/knowledge-base/collections/namespaces/blog/locales/%locale%/**/%original_file_name%'

