apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: tupynambalucas-dev
requires:
  - path: cortex/skaffold.yaml
    configs: ['cortex-dev']
  - path: platform/skaffold.yaml
    configs: ['platform-dev']
  - path: studio/skaffold.yaml
    configs: ['studio-dev']
