apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - traefik.yaml
  - otelcol.yaml
  - turbocache.yaml
  - headlamp.yaml
  - certmanager.yaml
  - grafana.yaml
  - prometheus.yaml
  - kubestatemetrics.yaml
  - loki.yaml
  - tempo.yaml
  - cloudflared.yaml

secretGenerator:
  - name: platform-secrets
    namespace: platform
    envs:
      - ../.env
  - name: cloudflare-api-token-secret
    namespace: cert-manager
    envs:
      - ../.env

generatorOptions:
  disableNameSuffixHash: true
