apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: platform
  labels:
    app: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: otel-collector
          imagePullPolicy: IfNotPresent
          command: ['/otelcol-contrib', '--config=/etc/otelcol-contrib/config.yaml']
          volumeMounts:
            - name: config-volume
              mountPath: /etc/otelcol-contrib
          ports:
            - name: otlp-grpc
              containerPort: 4317
            - name: otlp-http
              containerPort: 4318
            - name: fluentforward
              containerPort: 24224
          envFrom:
            - secretRef:
                name: platform-secrets
                optional: true
      volumes:
        - name: config-volume
          configMap:
            name: otel-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: platform
spec:
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
    - name: fluentforward
      port: 24224
      targetPort: 24224
  selector:
    app: otel-collector
