name: tupynambalucas-platform

networks:
  platform-net:
    name: tupynambalucas-platform-net
    driver: bridge

services:
  otel-collector:
    profiles: ['core']
    container_name: tupynambalucas-platform-otel
    build:
      context: ../../services/otel-collector
      dockerfile: Dockerfile
    command: ['--config=/etc/otelcol-contrib/config.yaml']
    volumes:
      - ../../services/otel-collector/config.yaml:/etc/otelcol-contrib/config.yaml:ro
    ports:
      - '24224:24224'
    environment:
      - GRAFANA_CLOUD_OTLP_ENDPOINT=${GRAFANA_CLOUD_OTLP_ENDPOINT}
      - GRAFANA_CLOUD_TOKEN=${GRAFANA_CLOUD_TOKEN}
    networks:
      platform-net:
        aliases:
          - otel-collector
          - otel-collector.platform.svc.cluster.local

  turbocache:
    profiles: ['core']
    container_name: tupynambalucas-platform-turbocache
    build:
      context: ../../services/turbocache
      dockerfile: Dockerfile
    ports:
      - '${TURBO_CACHE_PORT:-3008}:3000'
    environment:
      - STORAGE_PROVIDER=${STORAGE_PROVIDER}
      - STORAGE_PATH=${STORAGE_PATH}
      - STORAGE_PATH_USE_TMP_FOLDER=${STORAGE_PATH_USE_TMP_FOLDER}
      - TURBO_TOKEN=${TURBO_TOKEN}
      - AUTH_MODE=${AUTH_MODE}
      - LOG_LEVEL=${LOG_LEVEL}
      - ENABLE_STATUS_LOG=${ENABLE_STATUS_LOG}
      - LOG_MODE=${LOG_MODE}
      - HTTP2=${HTTP2}
      - READ_ONLY=${READ_ONLY}
    volumes:
      - ../data/cache:/data
    networks:
      - platform-net

  prometheus:
    profiles: ['core']
    container_name: tupynambalucas-platform-prometheus
    build:
      context: ../../services/prometheus
      dockerfile: Dockerfile
    ports:
      - '9090:9090'
    networks:
      platform-net:
        aliases:
          - prometheus
          - prometheus.platform.svc.cluster.local

  loki:
    profiles: ['core']
    container_name: tupynambalucas-platform-loki
    build:
      context: ../../services/loki
      dockerfile: Dockerfile
    ports:
      - '3100:3100'
    networks:
      platform-net:
        aliases:
          - loki
          - loki.platform.svc.cluster.local

  tempo:
    profiles: ['core']
    container_name: tupynambalucas-platform-tempo
    build:
      context: ../../services/tempo
      dockerfile: Dockerfile
    ports:
      - '3200:3200'
      - '4318:4318'
    networks:
      platform-net:
        aliases:
          - tempo
          - tempo.platform.svc.cluster.local

  grafana:
    profiles: ['core']
    container_name: tupynambalucas-platform-grafana
    build:
      context: ../../services/grafana
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
    volumes:
      - ../data/grafana:/var/lib/grafana
    networks:
      - platform-net
