name: tupynambalucas-platform

networks:
  platform-net:
    name: tupynambalucas-platform-net
    driver: bridge

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: tupynambalucas-platform-otel
    command: ['--config=/etc/otelcol-contrib/config.yaml']
    volumes:
      - ../../services/monitor/config.yaml:/etc/otelcol-contrib/config.yaml:ro
    ports:
      - '24224:24224'
    environment:
      - GRAFANA_CLOUD_OTLP_ENDPOINT=${GRAFANA_CLOUD_OTLP_ENDPOINT}
      - GRAFANA_CLOUD_TOKEN=${GRAFANA_CLOUD_TOKEN}
      - SENTRY_OTLP_ENDPOINT=${SENTRY_OTLP_ENDPOINT}
      - SENTRY_AUTH_HEADER=${SENTRY_AUTH_HEADER}
    networks:
      - platform-net

  turbocache:
    container_name: tupynambalucas-platform-turbocache
    build:
      context: ../../services/turbocache
      dockerfile: Dockerfile
    ports:
      - '${TURBO_CACHE_PORT:-3008}:3000'
    environment:
      - STORAGE_PROVIDER=${STORAGE_PROVIDER}
      - STORAGE_PATH=${STORAGE_PATH}
      - STORAGE_PATH_USE_TMP_FOLDER=${STORAGE_PATH_USE_TMP_FOLDER}
      - TURBO_TOKEN=${TURBO_TOKEN}
      - AUTH_MODE=${AUTH_MODE}
      - LOG_LEVEL=${LOG_LEVEL}
      - ENABLE_STATUS_LOG=${ENABLE_STATUS_LOG}
      - LOG_MODE=${LOG_MODE}
      - HTTP2=${HTTP2}
      - READ_ONLY=${READ_ONLY}
    volumes:
      - ../data/cache:/data
    networks:
      - platform-net
