apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-local-tupynambalucas-dev
  namespace: cortex
spec:
  secretName: local-tls-secret
  issuerRef:
    name: letsencrypt-cloudflare-dns
    kind: ClusterIssuer
  commonName: '*.lan.tupynambalucas.dev'
  dnsNames:
    - '*.lan.tupynambalucas.dev'
