apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: platform-dev
build:
  platforms: ['linux/amd64']
  local:
    push: false
    useDockerCLI: true
    useBuildkit: true
    tryImportMissing: true
    concurrency: 0
  artifacts:
    - image: turbocache
      context: services/turbocache
      docker:
        dockerfile: Dockerfile
    - image: headlamp
      context: services/headlamp
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        manual:
          - src: 'src/**/*'
            dest: '/home/headlamp'
            strip: 'src'
    - image: otelcol-contrib
      context: services/otelcol
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*'
            dest: '/etc/otelcol-contrib'
            strip: 'src'
    - image: prometheus
      context: services/prometheus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*'
            dest: '/etc/prometheus'
            strip: 'src'
    - image: loki
      context: services/loki
      docker:
        dockerfile: Dockerfile
    - image: tempo
      context: services/tempo
      docker:
        dockerfile: Dockerfile
    - image: tupynambalucas-platform-grafana
      context: services/grafana
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        manual:
          - src: 'src/**/*'
            dest: '/etc/grafana'
            strip: 'src'
manifests:
  kustomize:
    paths:
      - infrastructure/kubernetes
    buildArgs:
      - --load-restrictor=LoadRestrictionsNone
deploy:
  kubectl:
    hooks:
      before:
        - host:
            command:
              - kubectl
              - apply
              - -f
              - https://github.com/cert-manager/cert-manager/releases/download/v1.15.0/cert-manager.yaml
        - host:
            command:
              - kubectl
              - wait
              - --for=condition=Established
              - --timeout=60s
              - crd/certificates.cert-manager.io
              - crd/clusterissuers.cert-manager.io
        - host:
            command:
              - kubectl
              - rollout
              - status
              - -n
              - cert-manager
              - deployment/cert-manager-webhook
              - --timeout=60s
        - host:
            command:
              - kubectl
              - rollout
              - status
              - -n
              - cert-manager
              - deployment/cert-manager
              - --timeout=60s
        - host:
            command:
              - kubectl
              - rollout
              - status
              - -n
              - cert-manager
              - deployment/cert-manager-cainjector
              - --timeout=60s

profiles:
  - name: prod
    build:
      artifacts:
        - image: tupynambalucas-platform-grafana
          context: services/grafana
          docker:
            dockerfile: Dockerfile
            target: prod
          sync: {}
        - image: headlamp
          context: services/grafana
          docker:
            dockerfile: Dockerfile
            target: prod
          sync: {}
