name: tupynambalucas-platform

networks:
  platform-net:
    name: tupynambalucas-platform-net
    driver: bridge
  tupynambalucas-mcp-net:
    name: tupynambalucas-mcp-net
    driver: bridge

services:
  agentgateway:
    profiles: ['dev', 'prod', 'staging']
    image: cr.agentgateway.dev/agentgateway:v1.3.1
    container_name: tupynambalucas-mcp-agentgateway-${APP_ENV:-prod}
    ports:
      - '${GATEWAY_PORT:-3005}:8080' # Tráfego principal IAs
      - '15000:15000' # Web UI do AgentGateway
    volumes:
      - ../../services/agentgateway/config.yaml:/config.yaml
    command: ['-f', '/config.yaml']
    logging:
      driver: fluentd
      options:
        fluentd-address: 'host.docker.internal:24224'
        tag: 'agentgateway'
        fluentd-async: 'true'
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT:-http://otel-collector:4317}
    networks:
      platform-net:
        aliases:
          - agentgateway-metrics
      tupynambalucas-mcp-net:
        aliases:
          - tupynambalucas.internal.tools.mcp

  otel-collector:
    profiles: ['dev', 'prod', 'staging']
    image: otel/opentelemetry-collector-contrib:latest
    container_name: tupynambalucas-platform-otel-${APP_ENV}
    command: ['--config=/etc/otelcol-contrib/config.yaml']
    volumes:
      - ../../services/monitor/config.yaml:/etc/otelcol-contrib/config.yaml:ro
    ports:
      - '24224:24224'
    environment:
      - GRAFANA_CLOUD_OTLP_ENDPOINT=${GRAFANA_CLOUD_OTLP_ENDPOINT}
      - GRAFANA_CLOUD_TOKEN=${GRAFANA_CLOUD_TOKEN}
      - SENTRY_OTLP_ENDPOINT=${SENTRY_OTLP_ENDPOINT}
      - SENTRY_AUTH_HEADER=${SENTRY_AUTH_HEADER}
    networks:
      - platform-net

  turbocache:
    profiles: ['dev', 'prod', 'staging']
    container_name: tupynambalucas-platform-turbocache-${APP_ENV}
    build:
      context: ../../services/turbocache
      dockerfile: Dockerfile
    ports:
      - '${TURBO_CACHE_PORT:-3008}:3000'
    environment:
      - STORAGE_PROVIDER=${STORAGE_PROVIDER}
      - STORAGE_PATH=${STORAGE_PATH}
      - STORAGE_PATH_USE_TMP_FOLDER=${STORAGE_PATH_USE_TMP_FOLDER}
      - TURBO_TOKEN=${TURBO_TOKEN}
      - AUTH_MODE=${AUTH_MODE}
      - LOG_LEVEL=${LOG_LEVEL}
      - ENABLE_STATUS_LOG=${ENABLE_STATUS_LOG}
      - LOG_MODE=${LOG_MODE}
      - HTTP2=${HTTP2}
      - READ_ONLY=${READ_ONLY}
    volumes:
      - ../data/cache:/data
    networks:
      - platform-net
