services:
  frontend:
    restart: always

  backend:
    restart: always

  exporter:
    restart: always

  valkey:
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'valkey-cli ping | grep PONG']
      interval: 5s
      timeout: 5s
      retries: 5

  aide:
    restart: 'no'
